const db = require('./store');

const VAR_KEYS = ['--bg', '--bg-alt', '--surface', '--surface-2', '--text', '--text-dim', '--text-dimmer', '--accent', '--teal'];
const VAR_LABELS = {
  '--accent': 'Primary / buttons',
  '--teal': 'Secondary accent',
  '--bg': 'Page background',
  '--bg-alt': 'Alternate section background',
  '--surface': 'Cards & forms',
  '--surface-2': 'Card tint',
  '--text': 'Main text',
  '--text-dim': 'Secondary text',
  '--text-dimmer': 'Captions',
};

const PRESETS = {
  classic: { label: 'Classic (original)', dark: false, vars: { '--bg': '#FAF8F4', '--bg-alt': '#F1EDE4', '--surface': '#FFFFFF', '--surface-2': '#F5F1E9', '--text': '#181712', '--text-dim': '#5A5A52', '--text-dimmer': '#6E6D63', '--accent': '#E8672B', '--teal': '#0E8E7E' } },
  ocean: { label: 'Ocean', dark: false, vars: { '--bg': '#F5F9FD', '--bg-alt': '#E9F1F9', '--surface': '#FFFFFF', '--surface-2': '#EDF3FA', '--text': '#0F1C2E', '--text-dim': '#465468', '--text-dimmer': '#5E6C80', '--accent': '#1D6FE0', '--teal': '#0B8F8A' } },
  forest: { label: 'Forest', dark: false, vars: { '--bg': '#F7F8F3', '--bg-alt': '#ECEFE4', '--surface': '#FFFFFF', '--surface-2': '#F1F3EA', '--text': '#16210F', '--text-dim': '#4A5544', '--text-dimmer': '#5F6B58', '--accent': '#2F855A', '--teal': '#B45309' } },
  royal: { label: 'Royal', dark: false, vars: { '--bg': '#FAF8FD', '--bg-alt': '#F0EBF8', '--surface': '#FFFFFF', '--surface-2': '#F4F0FA', '--text': '#1B1330', '--text-dim': '#4F4668', '--text-dimmer': '#655C7E', '--accent': '#6D28D9', '--teal': '#0E7490' } },
  sunset: { label: 'Sunset', dark: false, vars: { '--bg': '#FFF9F5', '--bg-alt': '#FBEEE4', '--surface': '#FFFFFF', '--surface-2': '#FDF1E8', '--text': '#2B1810', '--text-dim': '#6A4A3C', '--text-dimmer': '#7C5B4C', '--accent': '#D62F55', '--teal': '#B7791F' } },
  midnight: { label: 'Midnight (dark)', dark: true, vars: { '--bg': '#0F1216', '--bg-alt': '#151A20', '--surface': '#1B2129', '--surface-2': '#212833', '--text': '#ECEFF4', '--text-dim': '#A9B2C0', '--text-dimmer': '#8791A2', '--accent': '#FF7A3D', '--teal': '#2DD4BF' } },
};

const FONTS = ['Space Grotesk', 'Manrope', 'Inter', 'Poppins', 'Montserrat', 'Roboto', 'Open Sans', 'Lato', 'Nunito', 'DM Sans', 'Work Sans', 'Playfair Display', 'Merriweather', 'Raleway', 'Rubik', 'Outfit', 'Sora', 'Plus Jakarta Sans'];

const hex = (h) => (/^#[0-9a-f]{6}$/i.test(h) ? h.toUpperCase() : null);
function rgb(h) {
  const n = parseInt(h.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
function lum(h) {
  const c = rgb(h).map((v) => {
    v /= 255;
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
}
const ratio = (a, b) => {
  const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
};
/** dark or white text, whichever reads better on this background */
const onColor = (bg) => (ratio('#12100D', bg) >= ratio('#FFFFFF', bg) ? '#12100D' : '#FFFFFF');

function resolved() {
  const t = db.data.settings.theme;
  const preset = PRESETS[t.preset] || PRESETS.classic;
  const vars = { ...preset.vars };
  for (const k of VAR_KEYS) if (t.vars && hex(t.vars[k])) vars[k] = hex(t.vars[k]);
  return { vars, dark: !!preset.dark && !(t.vars && t.vars['--bg'] && lum(vars['--bg']) > 0.4), t };
}

const isDefault = () => {
  const { vars, t } = resolved();
  return JSON.stringify(vars) === JSON.stringify(PRESETS.classic.vars) && t.fontHeading === 'Space Grotesk' && t.fontBody === 'Manrope' && +t.radiusCard === 18 && +t.radiusButton === 10;
};

function css() {
  const { vars, dark, t } = resolved();
  const A = rgb(vars['--accent']), T = rgb(vars['--text']), B = rgb(vars['--bg']), TEAL = rgb(vars['--teal']);
  const onA = onColor(vars['--accent']);
  const onT = onColor(vars['--teal']);
  const fh = FONTS.includes(t.fontHeading) ? t.fontHeading : 'Space Grotesk';
  const fb = FONTS.includes(t.fontBody) ? t.fontBody : 'Manrope';
  const rc = Math.max(0, Math.min(40, +t.radiusCard || 0));
  const rb = Math.max(0, Math.min(40, +t.radiusButton || 0));
  const decl = Object.entries(vars).map(([k, v]) => `${k}:${v}`).join(';');
  return `/* generated by the dashboard — do not edit */
:root{${decl};--accent-soft:rgba(${A},0.12);--teal-soft:rgba(${TEAL},0.10);--border:rgba(${T},0.10);--border-strong:rgba(${T},0.18);--font-head:'${fh}';--font-body:'${fb}'}
html,body{background:var(--bg);color:var(--text)}
.site-nav-row{background:rgba(${B},0.9)}
.grid-lines{background-image:linear-gradient(rgba(${T},0.05) 1px,transparent 1px),linear-gradient(90deg,rgba(${T},0.05) 1px,transparent 1px)}
.btn-primary{color:${onA};box-shadow:0 8px 24px -8px rgba(${A},0.55)}
.btn-primary:hover{box-shadow:0 12px 28px -8px rgba(${A},0.7)}
.btn-ghost{background:rgba(${T},0.04)}
.btn-ghost:hover{background:rgba(${T},0.08)}
.card:hover{border-color:rgba(${A},0.45)}
.cw-msg.user,.cw-input-row button,.qc-item.call{color:${onA}}
.step-num,.qc-item.mail{color:${onT}}
.cw-head{color:${onColor(vars['--accent'])}}
.cw-btn{color:${onA}}
.card{border-radius:${rc}px}
.btn-primary,.btn-ghost{border-radius:${rb}px}
body,input,textarea,select,button{font-family:var(--font-body),sans-serif}
h1,h2,h3,.eyebrow,.footer-head,.btn-primary,.btn-ghost,.step-num,.cw-head,.qc-item,[style*="Space Grotesk"]{font-family:var(--font-head),sans-serif !important}
${dark ? `.cw-input-row input,.field-input,#contact-form input,#contact-form textarea{background:var(--surface-2);color:var(--text)}
.credit-badge{box-shadow:0 0 0 1px rgba(255,255,255,0.12)}` : ''}
`;
}

/** Google Fonts stylesheet url for the chosen pair */
function fontsUrl() {
  const { t } = resolved();
  const fh = FONTS.includes(t.fontHeading) ? t.fontHeading : 'Space Grotesk';
  const fb = FONTS.includes(t.fontBody) ? t.fontBody : 'Manrope';
  const fam = (n) => 'family=' + n.replace(/ /g, '+') + ':wght@400;500;600;700;800';
  return 'https://fonts.googleapis.com/css2?' + [...new Set([fh, fb])].map(fam).join('&') + '&display=swap';
}

/** Inline-style colours that can't be reached from CSS variables are rewritten in the HTML string */
function tintHtml(html) {
  if (isDefault()) return html;
  const { vars, dark } = resolved();
  const A = rgb(vars['--accent']).join(',');
  html = html.split('255,122,61').join(A);
  if (dark) {
    const S = rgb(vars['--surface']).join(',');
    html = html.split('rgba(255,255,255,0.92)').join(`rgba(${S},0.92)`).split('rgba(255,255,255,0.78)').join(`rgba(${S},0.78)`);
  }
  return html;
}

module.exports = { PRESETS, FONTS, VAR_KEYS, VAR_LABELS, resolved, css, fontsUrl, tintHtml, isDefault, hex, ratio };
